### ISSUE TITLE
[DOCS] README 오타 수정

### ISSUE THREAD

**Issue by min731** [Emozis/AI#24]
📍Location
- README.md

📝Description
- Project Management(PM) - Tools & Technologies 항목의 'Dscode'
- Contact 항목의 'narae3759@gmil.com'

✅TODO
- [x] 'Dscode'를 'Discord'로 수정
- [x] 'narae3759@gmil'을 'narae3759@gmail.com'로 수정

👣ETC
- 꼼꼼히 확인하여 정확한 정보를 기입해주세요!

**Comment by MinkyoDev** [comment]
readme는 docs입니다~

**Comment by OHTaEH** [comment]
고맙다 정민아

**Comment by min731** [comment]
OHTaEH님, 'Dscord' -> 'Discord'로 수정 부탁드려요!
